#!/bin/bash

echo "🔧 Gmail Push Notification Setup for Fly.io"
echo "============================================="
echo ""
echo "Your webhook server is working perfectly, but Gmail push notifications"
echo "are not configured to point to your Fly.io app."
echo ""
echo "Here's how to fix it:"
echo ""
echo "1. First, check if Gmail push is currently configured:"
echo "   flyctl logs --app court-booker"
echo ""
echo "2. Update your environment variables:"
echo "   - WEBHOOK_URL should be: https://court-booker.fly.dev"
echo "   - GMAIL_PROJECT_ID should be set"  
echo "   - GMAIL_TOPIC_NAME should be set"
echo ""
echo "3. Run the Gmail push setup script:"
echo "   node src/scripts/setup-gmail-push.js"
echo ""
echo "4. This will configure Gmail to send push notifications to:"
echo "   https://court-booker.fly.dev/gmail/webhook"
echo ""
echo "5. Test by sending an email with 'Check' to courtbooker824@gmail.com"
echo "   Watch the logs: flyctl logs --app court-booker --live"
echo ""
echo "✅ Current Status:"
echo "   - Webhook server: ✅ Working (court-booker.fly.dev)"
echo "   - Email parsing: ✅ Working (detects 'Check' emails)"
echo "   - Availability check: ✅ Working (found 80 slots)"
echo "   - Email sending: ✅ Working (SMTP configured)"
echo "   - Gmail push notifications: ❌ Not configured"
echo ""
echo "📧 Manual triggers work! Try these:"
echo "   curl -X POST https://court-booker.fly.dev/gmail/process-emails"
echo "   curl -X POST https://court-booker.fly.dev/gmail/check-availability"
echo ""